### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by eluzhnica** [RexYing/diffpool#9] opened 2019-03-08 22:26 UTC
Would be good to list the exact commands needed to reproduce the results reported in the paper. Similar to how they're listed in the `example.sh` script.

**Comment by lenhhoxung86** [comment] 2019-03-11 16:27
So the commands in `example.sh` cannot reproduce the results reported in the paper?
Also, after finishing the running of the code, I had difficulty to interpret the result.
How can I get the final result? By averaging the best performance on each fold or something else?
btw, the figure is not intuitive and the folder `results` are not there by default.

**Comment by RexYing** [comment] 2019-03-14 23:59
I updated the .sh script for the exact commands.
thanks for suggestions

Yes average the performance for each iteration in all folds.

Yes you need to mkdir results. Hope that's not too much trouble. I'll add in example.sh

The assignment figure shows how each node is assigned to hyper-nodes (S matrix)
The graphs corresponds to visualizations of some of the data in each epoch.

**Comment by eluzhnica** [comment] 2019-03-15 00:23
@RexYing Thanks for the update!

I noticed that you added the command for DD and Enzymes. Do you think you can do something about the other datasets (Reddit, Collab, Proteins)? I know the datasets are not in this repo, so you can put a comment that the users need to download them before running the command.

**Comment by RexYing** [comment] 2019-07-24 22:57
close since it's added

**Closed by RexYing** 2019-07-24 22:57 UTC
